name: chat_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.3.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation:
  cupertino_icons:
  get:
  dio:
  flutter_secure_storage:
  shared_preferences:
  google_fonts:
  logging:
  change_app_package_name:
  stomp_dart_client:
  dropdown_button2:
  webview_flutter:
  desktop_webview_window:
  window_manager:
  chat_bubbles:
  flutter_chat_ui:
  file_picker:
  image_picker:
  open_filex:
  uuid:
  bubble:
  intl:
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints:
dependency_overrides:
  webview_flutter_wkwebview:
    git:
      url: https://github.com/stuartmorgan/packages
      path: packages/webview_flutter/webview_flutter_wkwebview
      ref: webview-macos
flutter:
  uses-material-design: true
  assets:
    - image/main.jpg
    - assets/messages.json